# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LibMecabSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  platform :ios, '10.3'

  # Pods for LibMecabSample
  pod 'mecab-ko'

  # Japanese dictionary
  pod 'mecab-naist-jdic-utf-8'

  # Korean dictionary
  pod 'mecab-ko-dic-utf-8'

end

target 'LibMecabSample-macos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  platform :osx, '10.11'

  # Pods for LibMecabSample-macos
  pod 'mecab-ko'

  # Japanese dictionary
  pod 'mecab-naist-jdic-utf-8'

  # Korean dictionary
  pod 'mecab-ko-dic-utf-8'

end
