# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pod-tester' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pod-tester
  pod 'mecab-naist-jdic-utf-8', :path => '../mecab-naist-jdic-utf-8'

end
